{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bsord-homepage.serviceAccountName" . }}
  labels:
{{ include "bsord-homepage.labels" . | nindent 4 }}
{{- end -}}
